server:
  port: 8083

spring:
  application:
    name: channel-service
  datasource:
    url: "jdbc:mysql://localhost:3306/chat-channel"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    profile: http://localhost:8081/profile
    friendship: http://localhost:8082/friendship
    socket: http://localhost:8085/socket


