server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #        - id: websocket_route
        #          uri: ws://localhost:8081
        #          predicates:
        #            - Path=/ws/**
        #          filters:
        #            - RemoveRequestHeader=Sec-WebSocket-Protocol
        #            - RemoveRequestHeader=Sec-WebSocket-Key
        #            - RemoveRequestHeader=Sec-WebSocket-Version
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: friendship_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/friendship/**
          filters:
            - StripPrefix=2
        - id: channel_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/channel/**
          filters:
            - StripPrefix=2